name: Pre-release types

on:
  push:
    branches:
      - 'rc/*'
    paths:
      - packages/types/**
  workflow_dispatch:
    inputs:
      parachainDocker:
        description: "Name of the parachain docker reference"
        type: string
        required: false
        default: "mangatasolutions/mangata-node:develop"
      branch:
        description: "Branch where to make pre release"
        type: string
        required: false
        default: ""

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  API_URL: "ws://127.0.0.1:9947"

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Clone mangata node repository
        uses: actions/checkout@v3
        with:
          repository: mangata-finance/mangata-node
          path: mangata-repo
          ref: develop

      - name: Setup Node version and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install websocat
        run: |
            cargo install websocat
        shell: bash

      - name: Replace parachain docker image reference in config
        working-directory: mangata-repo/devops/parachain-launch
        run: sed -i 's+mangatasolutions/mangata-node:.*+${{ github.event.inputs.parachainDocker }}+g' config.yml

      - name: Generate the config
        working-directory: mangata-repo/devops/parachain-launch
        run: npx @open-web3/parachain-launch generate config.yml

      - name: Run the Node
        working-directory: mangata-repo/devops/parachain-launch/output
        run: |
          docker-compose up -d --build
          docker ps

      - name: Sleep for 3 minutes
        run: sleep 180s

      - run: npm ci

      - run: npx nx run @mangata-finance/types:generate-metadata

      - run: npx nx run @mangata-finance/types:build-types

      - run: npx nx run @mangata-finance/types:lint

      - name: Add branch to project.json in order to perform pre-release
        if: ${{ github.event.inputs.branch != '' }}
        working-directory: packages/types
        run: |
          sed -i "/\"branches\": \[/a { \"name\": \"${{ github.event.inputs.branch }}\", \"channel\": \"${{ github.event.inputs.branch }}\", \"prerelease\": \"${{ github.event.inputs.branch }}\" }," project.json

      - name: Commit and push changes
        if: ${{ github.event.inputs.branch != '' }}
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          commit_message: "feat: type generation mangata node [only @mangata-finance/types]"

      - run: npx nx semantic-release @mangata-finance/types
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}




