name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - run: npm i

      - run: npx nx run-many --target=semantic-release --parallel=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate docs
        working-directory: packages/sdk
        run: npx typedoc src/index.ts --skipErrorChecking

      - name: Deploy github page for doc 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/sdk/docs # The folder the action should deploy.



